import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./_components/main/NavBar";
import QueryClientProvider from "./QueryClientProvider";
import Footer from "./_components/main/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Game Quest",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/logoGameQuest.svg",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#010125] overflow-x-hidden`}
      >
        <QueryClientProvider>
          <NavBar />
          {children}
          <Footer />
        </QueryClientProvider>
      </body>
    </html>
  );
}
